"use strict";
const API="https://api.github.com",HEADERS={"Accept":"application/vnd.github+json","X-GitHub-Api-Version":"2026-03-10"};
const P={commercial:"Dùng trong sản phẩm, dịch vụ hoặc hoạt động thương mại",modifications:"Sửa đổi mã nguồn, thêm locale và tạo bản Việt hóa",distribution:"Sao chép và phân phối phần mềm hoặc bản sửa đổi",private:"Sử dụng nội bộ hoặc riêng tư",patent:"Được cấp quyền bằng sáng chế trong phạm vi giấy phép",sublicense:"Cấp phép lại trong phạm vi giấy phép"};
const C={copyright:"Giữ thông báo bản quyền và văn bản giấy phép trong bản sao/phần đáng kể",changes:"Đánh dấu hoặc mô tả rõ nội dung đã thay đổi",source:"Khi nghĩa vụ phát sinh, cung cấp mã nguồn tương ứng",same:"Phần phái sinh thuộc copyleft phải tiếp tục dùng cùng giấy phép",network:"Người dùng tương tác qua mạng phải có cách nhận mã nguồn tương ứng",file:"Các file đã sửa phải tiếp tục giữ giấy phép gốc",library:"Thư viện sửa đổi phải giữ LGPL và cho phép thay thế/relink"};
const L={liability:"Không mặc nhiên chuyển trách nhiệm thiệt hại sang tác giả gốc",warranty:"Không quảng cáo rằng tác giả gốc bảo hành bản Việt hóa",trademark:"Không suy ra quyền dùng tên, logo hoặc nhãn hiệu",patent:"Không suy ra quyền cho mọi bằng sáng chế liên quan"};
const DB={
"mit":x("MIT License","MIT",["commercial-use","modifications","distribution","private-use"],["include-copyright"],["liability","warranty"]),
"apache-2.0":x("Apache License 2.0","Apache-2.0",["commercial-use","modifications","distribution","private-use","patent-use"],["include-copyright","document-changes"],["liability","warranty","trademark-use"]),
"bsd-2-clause":x("BSD 2-Clause Simplified License","BSD-2-Clause",["commercial-use","modifications","distribution","private-use"],["include-copyright"],["liability","warranty"]),
"bsd-3-clause":x("BSD 3-Clause New or Revised License","BSD-3-Clause",["commercial-use","modifications","distribution","private-use"],["include-copyright"],["liability","warranty","trademark-use"]),
"gpl-2.0":x("GNU General Public License v2.0","GPL-2.0",["commercial-use","modifications","distribution","private-use"],["include-copyright","document-changes","disclose-source","same-license"],["liability","warranty"]),
"gpl-3.0":x("GNU General Public License v3.0","GPL-3.0",["commercial-use","modifications","distribution","private-use","patent-use"],["include-copyright","document-changes","disclose-source","same-license"],["liability","warranty"]),
"lgpl-2.1":x("GNU Lesser General Public License v2.1","LGPL-2.1",["commercial-use","modifications","distribution","private-use"],["include-copyright","document-changes","disclose-source","same-license--library"],["liability","warranty"]),
"lgpl-3.0":x("GNU Lesser General Public License v3.0","LGPL-3.0",["commercial-use","modifications","distribution","private-use","patent-use"],["include-copyright","document-changes","disclose-source","same-license--library"],["liability","warranty"]),
"mpl-2.0":x("Mozilla Public License 2.0","MPL-2.0",["commercial-use","modifications","distribution","private-use","patent-use"],["include-copyright","disclose-source","same-license--file"],["liability","warranty","trademark-use"]),
"agpl-3.0":x("GNU Affero General Public License v3.0","AGPL-3.0",["commercial-use","modifications","distribution","private-use","patent-use"],["include-copyright","document-changes","disclose-source","network-use-disclose","same-license"],["liability","warranty"]),
"eupl-1.2":x("European Union Public Licence 1.2","EUPL-1.2",["commercial-use","modifications","distribution","private-use","patent-use"],["include-copyright","disclose-source","network-use-disclose","same-license"],["liability","warranty","trademark-use"]),
"unlicense":x("The Unlicense","Unlicense",["commercial-use","modifications","distribution","private-use"],[],["liability","warranty"]),
"cc0-1.0":x("Creative Commons Zero v1.0 Universal","CC0-1.0",["commercial-use","modifications","distribution","private-use"],[],["liability","warranty","patent-use","trademark-use"])
};
const SPECIAL={
"MIT":["Giữ copyright và toàn văn MIT License trong mọi bản sao hoặc phần đáng kể."],
"Apache-2.0":["Giữ NOTICE nếu dự án có; đánh dấu nổi bật các file đã sửa.","Có điều khoản cấp và chấm dứt quyền bằng sáng chế trong một số tranh chấp."],
"BSD-3-Clause":["Không dùng tên tác giả/tổ chức để chứng thực hoặc quảng bá nếu chưa được phép."],
"GPL-2.0":["Khi phân phối binary/bản sửa, phải cung cấp mã nguồn tương ứng theo GPL."],
"GPL-3.0":["Một số sản phẩm người dùng còn phải cung cấp thông tin cài đặt để chạy bản sửa."],
"LGPL-2.1":["App có thể dùng license khác nhưng phải cho phép sửa/thay thế hoặc relink thư viện LGPL."],
"LGPL-3.0":["App có thể dùng license khác nhưng phần thư viện sửa đổi phải tiếp tục tuân LGPL."],
"MPL-2.0":["Copyleft chủ yếu ở cấp file: file MPL đã sửa phải tiếp tục MPL khi phân phối."],
"AGPL-3.0":["Bản sửa đổi cho người dùng tương tác qua mạng phải có cách nhận source tương ứng."],
"EUPL-1.2":["Có điều khoản tương thích với danh sách license FOSS và phạm vi mạng đáng lưu ý."],
"Unlicense":["Mục tiêu gần phạm vi công cộng; hiệu lực phụ thuộc pháp luật và không có patent grant rõ."],
"CC0-1.0":["Không cấp quyền patent hoặc trademark rõ ràng."]
};
const $=id=>document.getElementById(id),el={form:$("licenseForm"),input:$("repoUrl"),btn:$("checkBtn"),error:$("inlineError"),overlay:$("modalOverlay"),modal:$("modal"),result:$("licenseResult"),close:$("closeModal"),toast:$("toast")};
let report="",lastFocus;
function x(name,spdx_id,permissions,conditions,limitations){return{name,spdx_id,permissions,conditions,limitations}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function safe(v){try{const u=new URL(v);return u.protocol==="https:"?u.href:"#"}catch{return"#"}}
function parse(v){v=v.trim().replace(/^git\+/,"").replace(/\.git\/?$/,"");let m=v.match(/^([A-Za-z0-9](?:[A-Za-z0-9-]{0,38}))\/([A-Za-z0-9._-]+)$/);if(m)return{owner:m[1],repo:m[2]};if(/^github\.com\//i.test(v))v="https://"+v;try{let u=new URL(v),a=u.pathname.split("/").filter(Boolean);if(!["github.com","www.github.com"].includes(u.hostname.toLowerCase())||a.length<2)return null;return{owner:a[0],repo:a[1].replace(/\.git$/,'')}}catch{return null}}
async function get(path,notFound=false){const r=await fetch(API+path,{headers:HEADERS}),remaining=r.headers.get("x-ratelimit-remaining");if(notFound&&r.status===404)return{data:null,remaining};if(!r.ok){let msg="";try{msg=(await r.json()).message||""}catch{}if(r.status===404)throw Error("Không tìm thấy repository hoặc repository không công khai.");if(r.status===403||r.status===429)throw Error("Đã chạm giới hạn GitHub API công khai. Hãy thử lại sau.");throw Error(msg||`GitHub API trả về lỗi ${r.status}.`)}return{data:await r.json(),remaining}}
function open(html){lastFocus=document.activeElement;el.result.innerHTML=html;el.overlay.classList.add("open");el.overlay.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";setTimeout(()=>el.modal.focus())}
function close(){el.overlay.classList.remove("open");el.overlay.setAttribute("aria-hidden","true");document.body.style.overflow="";lastFocus?.focus?.()}
function loading(repo){open(`<div class="loading"><div><div class="spinner"></div><h2>Đang kiểm tra</h2><p class="summary">${esc(repo)} · metadata, LICENSE và nghĩa vụ giấy phép</p></div></div>`)}
function mapPermission(k){return P[{"commercial-use":"commercial","modifications":"modifications","distribution":"distribution","private-use":"private","patent-use":"patent","sublicense":"sublicense"}[k]]||k}
function mapCondition(k){return C[{"include-copyright":"copyright","document-changes":"changes","disclose-source":"source","same-license":"same","network-use-disclose":"network","same-license--file":"file","same-license--library":"library"}[k]]||k}
function mapLimit(k){return L[{"liability":"liability","no-liability":"liability","warranty":"warranty","no-warranty":"warranty","trademark-use":"trademark","patent-use":"patent"}[k]]||k}
function family(l){let c=l.conditions||[];if(l.spdx_id==="AGPL-3.0")return"Copyleft mạng rất mạnh";if(l.spdx_id==="EUPL-1.2")return"Copyleft tương hỗ + mạng";if(c.includes("same-license"))return"Copyleft mạnh";if(c.includes("same-license--library"))return"Copyleft mức thư viện";if(c.includes("same-license--file"))return"Copyleft mức file";if(["Unlicense","CC0-1.0","0BSD"].includes(l.spdx_id))return"Gần phạm vi công cộng";return"Cho phép linh hoạt"}
function assess(l){let p=l.permissions||[],c=l.conditions||[],d=c.some(i=>["disclose-source","same-license","same-license--file","same-license--library","network-use-disclose"].includes(i));return{local:p.includes("modifications")?"Có":"Không rõ",dist:p.includes("distribution")?(d?"Có điều kiện":"Có"):"Không rõ",credit:c.includes("include-copyright")?"Bắt buộc":"Không bắt buộc",commercial:p.includes("commercial-use")?(d?"Có điều kiện":"Có"):"Không rõ",family:family(l)}}
function restrictions(l){let c=l.conditions||[],m=l.limitations||[],r=[];if(c.includes("include-copyright"))r.push("Không xóa thông báo bản quyền hoặc văn bản giấy phép phải giữ.");if(c.includes("same-license"))r.push("Không đóng mã phần phái sinh thuộc copyleft khi đã phân phối.");if(c.includes("same-license--file"))r.push("Không đổi sang license đóng cho các file MPL đã sửa.");if(c.includes("same-license--library"))r.push("Không đóng phần thư viện LGPL đã sửa hoặc ngăn relink/thay thế.");if(c.includes("network-use-disclose"))r.push("Không cung cấp bản sửa đổi qua mạng mà bỏ nghĩa vụ source.");if(m.some(x=>x==="trademark-use"))r.push("Không tự nhận quyền dùng tên, logo hoặc nhãn hiệu để quảng bá.");if(!(l.permissions||[]).includes("patent-use"))r.push("Không suy diễn rằng license cấp quyền cho mọi bằng sáng chế.");r.push("Không trình bày người Việt hóa như tác giả của phần mã gốc.");return[...new Set(r)]}
function score(label,val){let cls=val==="Có"?"yes":val==="Không"?"no":"maybe";return`<div class="score"><span>${esc(label)}</span><b class="${cls}">${esc(val)}</b></div>`}
function list(items,mapper,empty="Không có mục nào được liệt kê."){return items.length?items.map(i=>`<li><span>${esc(mapper(i))}</span></li>`).join(""):`<li><span>${empty}</span></li>`}
function reportText(repo,l,a,notes){return`KIỂM TRA GIẤY PHÉP GITHUB\nRepository: ${repo.full_name}\nGiấy phép: ${l.name} (${l.spdx_id})\n\nĐÁNH GIÁ\n- Việt hóa: ${a.local}\n- Phân phối: ${a.dist}\n- Ghi công: ${a.credit}\n- Thương mại: ${a.commercial}\n- Bản chất: ${a.family}\n\nĐƯỢC PHÉP\n${(l.permissions||[]).map(x=>"- "+mapPermission(x)).join("\n")}\n\nĐIỀU KIỆN\n${(l.conditions||[]).map(x=>"- "+mapCondition(x)).join("\n")||"- Không có mục được liệt kê"}\n\nLƯU Ý\n${notes.map(x=>"- "+x).join("\n")}\n\nKết quả là tóm tắt kỹ thuật, không phải tư vấn pháp lý.`}
function detected(repo,file,l,remaining){let a=assess(l),bad=restrictions(l),notes=[...(SPECIAL[l.spdx_id]||[]),`GitHub phát hiện từ file ${file?.path||"LICENSE"}.`,"Ghi rõ upstream, tác giả/chủ sở hữu, commit nền và phần đã thay đổi.","Kiểm tra thêm NOTICE, COPYING, AUTHORS, dependency, model và dataset."];report=reportText(repo,l,a,notes);el.result.innerHTML=`<header><div class="repo-line">Repository: <a href="${safe(repo.html_url)}" target="_blank">${esc(repo.full_name)}</a></div><span class="badge">SPDX · ${esc(l.spdx_id)}</span><h2 id="modalTitle">${esc(l.name)}</h2><p class="summary">${esc(repo.description||"Repository không có mô tả.")}</p></header><div class="score-grid">${score("Việt hóa",a.local)}${score("Phân phối",a.dist)}${score("Ghi công",a.credit)}${score("Thương mại",a.commercial)}${score("Bản chất",a.family)}</div><div class="analysis"><section class="box good"><h3>✅ Được phép</h3><ul>${list(l.permissions||[],mapPermission)}</ul></section><section class="box duty"><h3>⚠️ Điều kiện</h3><ul>${list(l.conditions||[],mapCondition)}</ul></section><section class="box bad"><h3>🚫 Không được suy diễn</h3><ul>${bad.map(x=>`<li><span>${esc(x)}</span></li>`).join("")}</ul></section><section class="box"><h3>📌 Lưu ý Việt hóa</h3><ul>${notes.map(x=>`<li><span>${esc(x)}</span></li>`).join("")}</ul></section><div class="notice box full"><b>Kết luận:</b> Có thể Việt hóa khi mục tương ứng là “Có”, nhưng trước phát hành phải hoàn thành toàn bộ nghĩa vụ license.</div><section class="box full"><h3>🤝 Liêm chính trước khi Fork</h3><ul><li><span>Không thay tên tác giả gốc bằng tên người Việt hóa.</span></li><li><span>Tách rõ bản dịch, mã sửa và tính năng mới.</span></li><li><span>Ưu tiên gửi locale/cải tiến chung về upstream bằng Pull Request.</span></li><li><span>Không dùng mục tiêu giáo dục để biện minh cho việc bỏ qua license.</span></li></ul></section></div><div class="actions"><button id="copyResult">Sao chép kết quả</button>${file?.html_url?`<a href="${safe(file.html_url)}" target="_blank">Mở LICENSE ↗</a>`:""}<a href="${safe(repo.html_url)}" target="_blank">Mở repository ↗</a></div><p class="fineprint">Nguồn: GitHub REST API · Lượt công khai còn lại: ${esc(remaining??"không rõ")}.</p>`;$("copyResult").onclick=copy}
function noLicense(repo,remaining){report=`KIỂM TRA GIẤY PHÉP\n${repo.full_name}\nKhông phát hiện LICENSE. Không nên tự ý sửa, phân phối hoặc thương mại hóa nếu chưa được cấp quyền.`;el.result.innerHTML=`<header><div class="repo-line">Repository: <a href="${safe(repo.html_url)}" target="_blank">${esc(repo.full_name)}</a></div><span class="badge warn">Không phát hiện LICENSE</span><h2 id="modalTitle">Không có quyền sử dụng mặc định</h2></header><div class="danger"><b>Cảnh báo:</b> Repository công khai không đồng nghĩa mã nguồn thuộc phạm vi công cộng. Luật bản quyền mặc định vẫn áp dụng.</div><div class="analysis" style="margin-top:11px"><section class="box bad"><h3>🚫 Không nên làm</h3><ul><li><span>Không sao chép để phát hành hoặc bán.</span></li><li><span>Không công bố bản Việt hóa như dự án được cấp phép.</span></li><li><span>Không tự thêm MIT/GPL cho mã bạn không sở hữu.</span></li></ul></section><section class="box"><h3>📌 Cách xử lý</h3><ul><li><span>Xin phép chủ sở hữu bằng văn bản.</span></li><li><span>Kiểm tra license trong thư mục con.</span></li><li><span>Chọn dự án thay thế có license rõ ràng.</span></li></ul></section></div><div class="actions"><button id="copyResult">Sao chép cảnh báo</button><a href="${safe(repo.html_url)}" target="_blank">Mở repository ↗</a></div><p class="fineprint">Lượt API còn lại: ${esc(remaining??"không rõ")}.</p>`;$("copyResult").onclick=copy}
function custom(repo,file,remaining){report=`KIỂM TRA GIẤY PHÉP\n${repo.full_name}\nCó file ${file?.path||"LICENSE"} nhưng GitHub không nhận diện SPDX. Phải đọc thủ công.`;el.result.innerHTML=`<header><div class="repo-line">Repository: <a href="${safe(repo.html_url)}" target="_blank">${esc(repo.full_name)}</a></div><span class="badge warn">SPDX · NOASSERTION</span><h2 id="modalTitle">Giấy phép tùy chỉnh hoặc không nhận diện</h2></header><div class="notice">Không thể tự động kết luận quyền Việt hóa, phân phối hoặc thương mại. Hãy đọc toàn văn và kiểm tra quyền sửa đổi, source, nhãn hiệu, patent và điều kiện bổ sung.</div><div class="actions"><button id="copyResult">Sao chép cảnh báo</button>${file?.html_url?`<a href="${safe(file.html_url)}" target="_blank">Đọc giấy phép ↗</a>`:""}<a href="${safe(repo.html_url)}" target="_blank">Mở repository ↗</a></div><p class="fineprint">Lượt API còn lại: ${esc(remaining??"không rõ")}.</p>`;$("copyResult").onclick=copy}
async function copy(){try{await navigator.clipboard.writeText(report)}catch{let t=document.createElement("textarea");t.value=report;document.body.append(t);t.select();document.execCommand("copy");t.remove()}el.toast.classList.add("show");setTimeout(()=>el.toast.classList.remove("show"),1600)}
async function check(raw){el.error.classList.remove("show");let p=parse(raw);if(!p){el.error.textContent="Link không hợp lệ. Nhập dạng https://github.com/owner/repo hoặc owner/repo.";el.error.classList.add("show");return}let full=`${p.owner}/${p.repo}`;loading(full);el.btn.disabled=true;el.btn.textContent="Đang kiểm tra…";try{let [rr,lr]=await Promise.all([get(`/repos/${encodeURIComponent(p.owner)}/${encodeURIComponent(p.repo)}`),get(`/repos/${encodeURIComponent(p.owner)}/${encodeURIComponent(p.repo)}/license`,true)]),repo=rr.data,file=lr.data,remaining=lr.remaining??rr.remaining;if(!file||!file.license)return noLicense(repo,remaining);let d=file.license,key=String(d.key||"").toLowerCase(),spdx=d.spdx_id||"NOASSERTION";if(key==="other"||spdx==="NOASSERTION")return custom(repo,file,remaining);let l=DB[key]||x(d.name,spdx,[],[],[]);try{let z=(await get(`/licenses/${encodeURIComponent(key)}`)).data;l={...l,...z,name:z.name||d.name,spdx_id:z.spdx_id||spdx}}catch(e){console.warn("Dùng dữ liệu dự phòng",e)}detected(repo,file,l,remaining)}catch(e){el.result.innerHTML=`<div class="loading"><div><h2 id="modalTitle">Không thể kiểm tra</h2><p class="summary">${esc(e.message||"Lỗi không xác định")}</p></div></div>`}finally{el.btn.disabled=false;el.btn.textContent="Kiểm tra ngay"}}
el.form.addEventListener("submit",e=>{e.preventDefault();check(el.input.value)});document.querySelectorAll("[data-repo]").forEach(b=>b.onclick=()=>{el.input.value=b.dataset.repo;check(b.dataset.repo)});el.close.onclick=close;el.overlay.onclick=e=>{if(e.target===el.overlay)close()};document.addEventListener("keydown",e=>{if(e.key==="Escape"&&el.overlay.classList.contains("open"))close()});el.input.focus();
